version: '3.1'

services:
    note-app:
        image: filipstenbeck/note-app:1.0.2
        restart: always
        env_file:
            - ./.env

        ports:
            - 3000:3000
    note-app-api:
        image: filipstenbeck/note-app-api:1.0.0
        restart: always

        ports:
            - 4000:4000
